[workspace]

members = [
  "chapter/01-getting-started",
  "chapter/02-guessing-game",
  "chapter/03-common-concepts",
  "chapter/04-understanding-ownership",
  "chapter/05-using-structs",
  "chapter/06-enums-patterns",
  "chapter/07-growing-projects",
  "chapter/08-common-collections",
]
